version: '3.7'
services:
  app:
    build: .
    environment:
      CKAN_SITE_URL: http://localhost:8080
      DATABASE_URL: postgresql://ckan:ckan@db/ckan
      SOLR_URL: http://solr:8983/solr/ckan
      FGDC2ISO_URL: http://fgdc2iso:8080/fgdc2iso
      REDIS_URL: redis:6379
    depends_on:
      - redis
      - db
      - solr
      - fgdc2iso
    command: app --wait-for-dependencies
    volumes:
      - .:/opt/catalog-app
      - ckan:/usr/lib/ckan
      - /tmp/ckan
    ports:
      - "5000:5000"
      - "8080:80"

  db:
    image: datagov/catalog-db:latest
    environment:
      POSTGRES_USER: postgres
      DB_CKAN_USER: ckan
      DB_CKAN_PASSWORD: pass
      DB_CKAN_DB: ckan
      DB_PYCSW_DB: pycsw

  fgdc2iso:
    image: datagov/catalog-fgdc2iso:latest
    environment:
      SIGNATURE:

  redis:
    build: ./docker/redis

  solr:
    image: datagov/catalog-solr:latest


volumes:
  ckan:
