app:
  build: .
  environment:
    CKAN_SITE_URL: http://catalog.dev
  links:
   - redis
   - db
   - solr
   - fgdc2iso
  command: app --wait-for-dependencies
  volumes:
   - /var/tmp/ckan/csv:/var/tmp/ckan/csv
harvester-fetch-consumer:
  build: .
  links:
   - app
   - redis
   - db
   - solr
   - fgdc2iso
  command: fetch-consumer --wait-for-dependencies
harvester-gather-consumer:
  build: .
  links:
   - app
   - redis
   - db
   - solr
   - fgdc2iso
  command: gather-consumer --wait-for-dependencies
redis:
  image: redis
db:
  image: datagov/catalog-db
  environment:
    POSTGRES_USER: postgres
    DB_CKAN_USER: ckan
    DB_CKAN_PASSWORD: pass
    DB_CKAN_DB: ckan
    DB_PYCSW_DB: pycsw
solr:
  image: datagov/catalog-solr
fgdc2iso:
  image: datagov/catalog-fgdc2iso
  environment:
    SIGNATURE:
pycsw:
  image: datagov/catalog-pycsw
  links:
   - app
   - db
  command: /entrypoint.sh --wait-for-dependencies
nginx:
    image: datagov/catalog-nginx
    ports:
      - "80:80"
    links:
      - app
      - pycsw
    command: /entrypoint.sh --wait-for-dependencies
scheduler:
  image: datagov/catalog-scheduler
  links:
   - redis
   - db
   - solr
   - fgdc2iso
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock 
